---
title: 'location-2006'
author: "Batta Liu"
date: '2018-03-08'
output: html_document
---

```{r packages, echo=FALSE}
library(plyr)
library(dplyr)
library(readr)
library(stringr)
library(rvest)
library(Rcrawler)
library(data.table)
library(RQGIS)
library(rgdal)
library(sp)
library(raster)
library(maptools)
library(stringr)
library(data.table)
```

```{r}
mine.sdf <- read.csv("/Users/batta/Dropbox/phd4/monopsony/mining-r/mine-55th-full.csv")
unique(mine.sdf$INSET)
mine.sdf <- mine.sdf %>% 
	filter(INSET == "BASEMETAL" | INSET == "PRECIOUS" | INSET == "FERROUS") %>% 
	filter(STATUS !="C" & STATUS !="CXR" & STATUS !="XR" & is.na(COMPANY)==FALSE)

coordinates(mine.sdf) <- c("LONGITUDE", "LATITUDE")
class(mine.sdf)
summary(mine.sdf)
map.sdf.06 <- readOGR("/Users/batta/Dropbox/phd4/monopsony/map/2006_csd_map/gcsd000a06a_e", "gcsd000a07a_e")
proj4string(mine.sdf) <- crs(map.sdf.06)
summary(map.sdf.06)
mine.attribute <- over(mine.sdf, map.sdf.06)
mine.bind <- spCbind(mine.sdf, mine.attribute)
summary(mine.bind)
matched2.CSD <- as.data.frame(mine.bind)
# matchedCSD.direct <- write_csv(match.mine.8081, "/Users/batta/Dropbox/phd4/monopsony/mining-r/mine-30th-matched1.csv")

matched2.CSD <- matched2.CSD %>% 
	dplyr::select(PROVINCE, COMPANY, MINESITE, LOCATION, CSDUID,CSDNAME,INSET, PRODUCT, MAPSYM, GROUP, MINETYPE,STATUS)
write_csv(matched2.CSD, "/Users/batta/Dropbox/phd4/monopsony/mining-r/mine-55th-matched3.csv")
```
